management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    chaosmonkey:
      enabled: true
spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    assaults:
      level: 5
      latency-active: true
      latency-range-start: 1000
      latency-range-end: 2000
      exceptions-active: true
      exception:
        type: java.lang.RuntimeException
        arguments:
          - className: "java.lang.String"
            value: "test exception"
      watched-custom-services: me.home.r4jex.circuitbreaker4.domain.BackendService.ping

