management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTrasitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - me.home.r4jex.api.domain.exception.BizException
    instances:
      BackendB.circuit:
        baseConfig: default
      BackednC.circuit:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  bulkhead:
    instances:
      BackendB.bulkhead:
        maxConcurrentCalls: 100
      BackendC.bulkhead:
        maxWaitDuration: 10ms
        maxConcurrentCalls: 20
  timelimiter:
    instances:
      BackendB.timelimiter:
        cancelRunningFuture: false
        timeoutDuration: 1s
      BackendC.timelimiter:
        cancelRunningFuture: true
        timeoutDurations: 1s